# Caution: this file may be regenerated by SOPC Builder.  User edits will be lost.
project_open -current_revision "/home/user5/spring11/smr2167/smr2167_lab3/lab3.qpf"
set_global_assignment -name VHDL_FILE altera_europa_support.vhd
project_close